CREATE TYPE price AS
(
    number        NUMERIC,
    currency_code TEXT
);

CREATE TYPE "account_type" AS ENUM (
    'Assets',
    'Liabilities',
    'Expenses',
    'Income',
    'Equity'
    );

CREATE TABLE IF NOT EXISTS "transaction"
(
    "id"            BIGINT  NOT NULL UNIQUE,
    "date"          DATE    NOT NULL,
    "completed"     BOOLEAN NOT NULL,
    "payee"         TEXT    NOT NULL,
    "narration"     TEXT,
    "external_id"   TEXT    NOT NULL,
    --  bit 0: double entry valide
    --  bit 1: catégorisé
    --  bit 2: réconcilié
    "classified_at" TIMESTAMP,
    "balanced_at"   TIMESTAMP,
    "reconciled_at" TIMESTAMP,
    "category_id"   INTEGER,
    PRIMARY KEY ("id")
);


COMMENT ON COLUMN "transaction"."classified_at" IS ' bit 0: double entry valide
 bit 1: catégorisé
 bit 2: réconcilié';


CREATE TABLE IF NOT EXISTS "posting"
(
    "id"                 BIGINT NOT NULL UNIQUE,
    "transaction_id"     BIGINT NOT NULL,
    -- ENUM
    "account_id"         BIGINT NOT NULL,
    "amount"             price  NOT NULL,
    -- position_id when we sold it
    "origin_position_id" INTEGER,
    "price_amount"       price,
    "tcr_id"             INTEGER,
    PRIMARY KEY ("id")
);

COMMENT ON COLUMN "posting"."account_id" IS 'ENUM';
COMMENT ON COLUMN "posting"."origin_position_id" IS 'position_id when we sold it';

CREATE TABLE IF NOT EXISTS "position"
(
    "id"               BIGINT  NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "date"             DATE    NOT NULL,
    "posting_id"       BIGINT  NOT NULL,
    "number"           NUMERIC NOT NULL,
    "ticker_symbol_id" INTEGER NOT NULL,
    "amount"           price   NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ticker_symbol"
(
    "id"   INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name" TEXT    NOT NULL UNIQUE,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "transaction_classifier_rule"
(
    "id"         INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "rule"       TEXT    NOT NULL,
    "account_id" BIGINT  NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "account"
(
    "id"   BIGINT       NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "type"  ACCOUNT_TYPE NOT NULL,
    "name"  TEXT         NOT NULL,
    "alias" TEXT         NOT NULL,
    "icon"  TEXT         NOT NULL,
    "color" TEXT         NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "bank_account"
(
    "id"          BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
    "name"        TEXT   NOT NULL,
    "account_id"  BIGINT NOT NULL,
    "external_id" TEXT   NOT NULL,
    PRIMARY KEY ("id")
);

ALTER TABLE "position"
    ADD FOREIGN KEY ("posting_id") REFERENCES "posting" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "posting"
    ADD FOREIGN KEY ("transaction_id") REFERENCES "transaction" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "position"
    ADD FOREIGN KEY ("ticker_symbol_id") REFERENCES "ticker_symbol" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "posting"
    ADD FOREIGN KEY ("origin_position_id") REFERENCES "position" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "posting"
    ADD FOREIGN KEY ("tcr_id") REFERENCES "transaction_classifier_rule" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "posting"
    ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "transaction_classifier_rule"
    ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "bank_account"
    ADD FOREIGN KEY ("account_id") REFERENCES "account" ("id")
        ON UPDATE NO ACTION ON DELETE NO ACTION;
