// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Line from "../../microchart/src/Line.res.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let months = [
  "Jan",
  "Fév",
  "Mar",
  "Avr",
  "Mai",
  "Juin",
  "Juil",
  "Août",
  "Sep",
  "Oct",
  "Nov",
  "Déc"
];

function init() {
  let appData = Stdlib_Option.flatMap(Stdlib_Option.flatMap(Primitive_option.fromNullable(document.getElementById("app-data")), el => Primitive_option.fromNullable(el.textContent)), s => {
    try {
      return JSON.parse(s);
    } catch (exn) {
      return;
    }
  });
  let match = Primitive_option.fromNullable(document.getElementById("net-worth-history-chart"));
  if (appData === undefined) {
    return;
  }
  if (match === undefined) {
    return;
  }
  let chartData = Line.parseChart(appData);
  Line.make(Primitive_option.valFromOption(match), chartData.series, chartData.options);
}

addEventListener("DOMContentLoaded", init);

export {
  months,
  init,
}
/*  Not a pure module */
