apiVersion: v1
kind: Pod
metadata:
  name: maille-dev
  labels:
    app: maille
    env: dev
spec:
  containers:
    - name: app
      image: localhost/maille-dev:latest
      ports:
        - containerPort: 13000
          hostPort: 13000
      envFrom:
        - configMapRef:
            name: config
      env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: maille-database-url
              key: database
      volumeMounts:
        - name: source
          mountPath: /app
        - name: go-mod-cache
          mountPath: /go/pkg/mod
        - name: go-build-cache
          mountPath: /home/srm/.cache/go-build
  volumes:
    - name: source
      hostPath:
        path: /mnt/data/src/go/maille
        type: Directory
    - name: go-mod-cache
      persistentVolumeClaim:
        claimName: go-mod-cache
    - name: go-build-cache
      persistentVolumeClaim:
        claimName: go-build-cache
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  TRACING_ENDPOINT: docker-monitoring-collector:4317
