DO $$ BEGIN
  CREATE TYPE account_type AS ENUM ('Assets', 'Liabilities', 'Expenses', 'Income', 'Equity');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS currency (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS account (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type account_type NOT NULL,
  name text NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_account (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  account_id bigint NOT NULL REFERENCES account(id),
  external_id text NOT NULL
);

CREATE TABLE IF NOT EXISTS transaction_classifier_rule (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rule text NOT NULL,
  account_id bigint NOT NULL REFERENCES account(id)
);

CREATE TABLE IF NOT EXISTS transaction (
  id bigint PRIMARY KEY,
  date date NOT NULL,
  completed boolean NOT NULL,
  payee text NOT NULL,
  narration text,
  external_id text NOT NULL,
  classified_at timestamp,
  balanced_at timestamp,
  reconciled_at timestamp
);

CREATE TABLE IF NOT EXISTS ticker_symbol (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS posting (
  id bigint PRIMARY KEY,
  transaction_id bigint NOT NULL REFERENCES transaction(id),
  account_id bigint NOT NULL REFERENCES account(id),
  amount numeric NOT NULL,
  currency_id integer NOT NULL REFERENCES currency(id),
  origin_position_id integer,
  price_amount numeric,
  price_currency_id integer REFERENCES currency(id),
  tcr_id integer REFERENCES transaction_classifier_rule(id)
);

CREATE TABLE IF NOT EXISTS position (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  posting_id bigint NOT NULL REFERENCES posting(id),
  number numeric NOT NULL,
  ticker_symbol_id integer NOT NULL REFERENCES ticker_symbol(id),
  amount numeric NOT NULL,
  currency_id integer NOT NULL REFERENCES currency(id)
);

DO $$ BEGIN
  ALTER TABLE posting
    ADD CONSTRAINT posting_origin_position_id_fkey
    FOREIGN KEY (origin_position_id) REFERENCES position(id);
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

INSERT INTO account (type, name)
SELECT 'Expenses', 'Other'
WHERE NOT EXISTS (
  SELECT 1 FROM account WHERE type = 'Expenses' AND name = 'Other'
);

INSERT INTO currency (name) VALUES ('EUR'), ('USD'), ('GBP')
ON CONFLICT (name) DO NOTHING;
