// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.js";

let svgNS = "http://www.w3.org/2000/svg";

let InvalidJson = /* @__PURE__ */Primitive_exceptions.create("Core.InvalidJson");

function optField(v, decode) {
  if (v !== undefined && v !== null) {
    return Primitive_option.some(decode(v));
  }
}

function asString(v) {
  if (typeof v === "string") {
    return v;
  }
  throw {
    RE_EXN_ID: InvalidJson,
    _1: {
      TAG: "InvalidString",
      _0: ""
    },
    Error: new Error()
  };
}

function asFloat(v) {
  if (typeof v === "number") {
    return v;
  }
  throw {
    RE_EXN_ID: InvalidJson,
    _1: {
      TAG: "InvalidFloat",
      _0: ""
    },
    Error: new Error()
  };
}

function asInt(v) {
  if (typeof v === "number") {
    return v | 0;
  }
  throw {
    RE_EXN_ID: InvalidJson,
    _1: {
      TAG: "InvalidInt",
      _0: ""
    },
    Error: new Error()
  };
}

function asStringArray(v) {
  if (Array.isArray(v)) {
    return v.map(value => {
      if (typeof value === "string") {
        return value;
      }
      throw {
        RE_EXN_ID: InvalidJson,
        _1: {
          TAG: "InvalidString",
          _0: "in array"
        },
        Error: new Error()
      };
    });
  }
  throw {
    RE_EXN_ID: InvalidJson,
    _1: {
      TAG: "InvalidStringArray",
      _0: ""
    },
    Error: new Error()
  };
}

let palette = [
  "#58a6ff",
  "#3fb950",
  "#f0883e",
  "#a371f7",
  "#f85149",
  "#39d353",
  "#ffa657",
  "#79c0ff"
];

function getColor(colorsOpt, i) {
  let colors = colorsOpt !== undefined ? colorsOpt : palette;
  return Stdlib_Option.getOr(colors[Primitive_int.mod_(i, colors.length)], "#58a6ff");
}

function el(tag, attrs) {
  let e = document.createElementNS(svgNS, tag);
  attrs.forEach(param => {
    e.setAttribute(param[0], param[1]);
  });
  return e;
}

function elIn(tag, attrs, parent) {
  let e = el(tag, attrs);
  parent.appendChild(e);
  return e;
}

function svgEl(w, h, container) {
  container.innerHTML = "";
  return elIn("svg", [
    [
      "viewBox",
      `0 0 ` + w.toString() + ` ` + h.toString()
    ],
    [
      "width",
      "100%"
    ],
    [
      "height",
      "100%"
    ],
    [
      "xmlns",
      svgNS
    ],
    [
      "style",
      "display:block;overflow:visible"
    ]
  ], container);
}

function group(transformOpt, parent) {
  let transform = transformOpt !== undefined ? transformOpt : "";
  return elIn("g", transform === "" ? [] : [[
        "transform",
        transform
      ]], parent);
}

function f2(v) {
  return v.toFixed(2);
}

function line(parent, x1, y1, x2, y2, strokeOpt, widthOpt) {
  let stroke = strokeOpt !== undefined ? strokeOpt : "#21262d";
  let width = widthOpt !== undefined ? widthOpt : "1";
  elIn("line", [
    [
      "x1",
      x1.toFixed(2)
    ],
    [
      "y1",
      y1.toFixed(2)
    ],
    [
      "x2",
      x2.toFixed(2)
    ],
    [
      "y2",
      y2.toFixed(2)
    ],
    [
      "stroke",
      stroke
    ],
    [
      "stroke-width",
      width
    ]
  ], parent);
}

function rect(parent, x, y, w, h, fill, rxOpt) {
  let rx = rxOpt !== undefined ? rxOpt : "2";
  elIn("rect", [
    [
      "x",
      x.toFixed(2)
    ],
    [
      "y",
      y.toFixed(2)
    ],
    [
      "width",
      w.toFixed(2)
    ],
    [
      "height",
      h.toFixed(2)
    ],
    [
      "fill",
      fill
    ],
    [
      "rx",
      rx
    ]
  ], parent);
}

function path(parent, d, attrs) {
  elIn("path", [[
      "d",
      d
    ]].concat(attrs), parent);
}

function circle(parent, cx, cy, r, attrs) {
  elIn("circle", [
    [
      "cx",
      cx.toFixed(2)
    ],
    [
      "cy",
      cy.toFixed(2)
    ],
    [
      "r",
      r.toFixed(2)
    ]
  ].concat(attrs), parent);
}

function text(parent, x, y, content, attrs) {
  let t = elIn("text", [
    [
      "x",
      x.toFixed(2)
    ],
    [
      "y",
      y.toFixed(2)
    ]
  ].concat(attrs), parent);
  t.innerHTML = content;
  return t;
}

function makeTooltip() {
  let d = document.createElement("div");
  let s = d.style;
  s.position = "fixed";
  s.pointerEvents = "none";
  s.opacity = "0";
  s.background = "#1c2128";
  s.border = "1px solid #30363d";
  s.borderRadius = "6px";
  s.padding = "5px 10px";
  s.fontSize = "12px";
  s.color = "#e6edf3";
  s.transition = "opacity .15s";
  s.zIndex = "9999";
  s.whiteSpace = "nowrap";
  document.body.appendChild(d);
  return {
    el: d
  };
}

function showTip(tip, html, e) {
  tip.el.innerHTML = html;
  let s = tip.el.style;
  s.opacity = "1";
  s.left = (e.clientX + 12 | 0).toString() + `px`;
  s.top = (e.clientY - 28 | 0).toString() + `px`;
}

function moveTip(tip, e) {
  let s = tip.el.style;
  s.left = (e.clientX + 12 | 0).toString() + `px`;
  s.top = (e.clientY - 28 | 0).toString() + `px`;
}

function hideTip(tip) {
  let s = tip.el.style;
  s.opacity = "0";
}

function removeTip(tip) {
  tip.el.remove();
}

function niceMax(vals) {
  let max = Stdlib_Array.reduce(vals, 0, (acc, v) => {
    if (v > acc) {
      return v;
    } else {
      return acc;
    }
  });
  if (max === 0) {
    return 10;
  }
  let mag = 10 ** (Math.log10(max) | 0);
  return Math.ceil(max / mag) * mag;
}

function linspace(min, max, n) {
  return Stdlib_Array.fromInitializer(n, i => min + (max - min) * i / (n - 1 | 0));
}

function fmtVal(v) {
  if (Math.abs(v) >= 1000000) {
    return (v / 1000000).toFixed(1) + `M`;
  } else if (Math.abs(v) >= 1000) {
    return (v / 1000).toFixed(1) + `K`;
  } else if (v === (v | 0)) {
    return (v | 0).toString();
  } else {
    return v.toFixed(2);
  }
}

export {
  svgNS,
  InvalidJson,
  optField,
  asString,
  asFloat,
  asInt,
  asStringArray,
  palette,
  getColor,
  el,
  elIn,
  svgEl,
  group,
  f2,
  line,
  rect,
  path,
  circle,
  text,
  makeTooltip,
  showTip,
  moveTip,
  hideTip,
  removeTip,
  niceMax,
  linspace,
  fmtVal,
}
/* No side effect */
