// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "./Core.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function parseSeries(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let name = json.name;
    if (typeof name === "string") {
      let rawData = json.data;
      if (Array.isArray(rawData)) {
        let area = json.area;
        if (typeof area === "boolean") {
          let dashed = json.dashed;
          if (typeof dashed === "boolean") {
            let data = rawData.map(Core.asFloat);
            let color = Core.optField(json.color, Core.asString);
            return {
              name: name,
              data: data,
              color: color,
              area: area,
              dashed: dashed
            };
          }
          throw {
            RE_EXN_ID: Core.InvalidJson,
            _1: {
              TAG: "InvalidData",
              _0: ""
            },
            Error: new Error()
          };
        }
        throw {
          RE_EXN_ID: Core.InvalidJson,
          _1: {
            TAG: "InvalidData",
            _0: ""
          },
          Error: new Error()
        };
      }
      throw {
        RE_EXN_ID: Core.InvalidJson,
        _1: {
          TAG: "InvalidData",
          _0: ""
        },
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidData",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidData",
      _0: ""
    },
    Error: new Error()
  };
}

function parseOptions(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let smooth = json.smooth;
    if (typeof smooth === "boolean") {
      let points = json.points;
      if (typeof points === "boolean") {
        return {
          width: Core.optField(json.width, Core.asFloat),
          height: Core.optField(json.height, Core.asFloat),
          labels: Core.optField(json.labels, Core.asStringArray),
          yTicks: Core.optField(json.yTicks, Core.asInt),
          smooth: smooth,
          points: points,
          colors: Core.optField(json.colors, Core.asStringArray)
        };
      }
      throw {
        RE_EXN_ID: Core.InvalidJson,
        _1: {
          TAG: "InvalidOption",
          _0: ""
        },
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidOption",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidOption",
      _0: ""
    },
    Error: new Error()
  };
}

function parseChart(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let rawSeries = json.series;
    if (Array.isArray(rawSeries)) {
      let rawOpts = json.options;
      let series = rawSeries.map(parseSeries);
      let options = rawOpts !== undefined && rawOpts !== null ? parseOptions(rawOpts) : ({
          width: undefined,
          height: undefined,
          labels: undefined,
          yTicks: undefined,
          smooth: false,
          points: false,
          colors: undefined
        });
      return {
        series: series,
        options: options
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidChart",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidChart",
      _0: ""
    },
    Error: new Error()
  };
}

function make(container, series, opts) {
  let w = Stdlib_Option.getOr(opts.width, 600);
  let h = Stdlib_Option.getOr(opts.height, 240);
  let yTicks = Stdlib_Option.getOr(opts.yTicks, 5);
  let colors = Stdlib_Option.getOr(opts.colors, Core.palette);
  let nPoints = Stdlib_Array.reduce(series, 0, (acc, s) => Primitive_int.max(acc, s.data.length));
  let labels = Stdlib_Option.getOr(opts.labels, Stdlib_Array.fromInitializer(nPoints, i => (i + 1 | 0).toString()));
  let allVals = series.flatMap(s => s.data);
  let maxVal = Core.niceMax(allVals);
  let plotW = w - 50 - 16;
  let plotH = h - 20 - 36;
  let step = plotW / (nPoints - 1 | 0);
  let svg = Core.svgEl(w, h, container);
  let g = Core.group(`translate(` + Core.f2(50) + `,` + Core.f2(20) + `)`, svg);
  Core.linspace(0, maxVal, yTicks).forEach(v => {
    let y = plotH - v / maxVal * plotH;
    Core.line(g, 0, y, plotW, y, undefined, undefined);
    Core.text(g, -6, y + 4, Core.fmtVal(v), [
      [
        "text-anchor",
        "end"
      ],
      [
        "fill",
        "#8b949e"
      ],
      [
        "font-size",
        "11"
      ]
    ]);
  });
  labels.forEach((lbl, i) => {
    let x = i * step;
    Core.text(g, x, plotH + 18, lbl, [
      [
        "text-anchor",
        "middle"
      ],
      [
        "fill",
        "#8b949e"
      ],
      [
        "font-size",
        "11"
      ]
    ]);
  });
  let tip = Core.makeTooltip();
  series.forEach((s, si) => {
    let c = Stdlib_Option.getOr(s.color, Core.getColor(colors, si));
    let pts = s.data.map((v, i) => [
      i * step,
      plotH - v / maxVal * plotH
    ]);
    let d;
    if (opts.smooth && pts.length > 2) {
      let match = pts[0];
      let init = `M` + Core.f2(match[0]) + `,` + Core.f2(match[1]);
      d = Stdlib_Array.reduceWithIndex(pts, init, (acc, param, i) => {
        if (i === 0) {
          return acc;
        }
        let cy = param[1];
        let cx = param[0];
        let match = pts[i - 1 | 0];
        let cpx = (match[0] + cx) / 2;
        return acc + (` C` + Core.f2(cpx) + `,` + Core.f2(match[1]) + ` ` + Core.f2(cpx) + `,` + Core.f2(cy) + ` ` + Core.f2(cx) + `,` + Core.f2(cy));
      });
    } else {
      d = pts.map((param, i) => (
        i === 0 ? "M" : "L"
      ) + Core.f2(param[0]) + `,` + Core.f2(param[1])).join(" ");
    }
    if (s.area) {
      let match$1 = pts[pts.length - 1 | 0];
      let match$2 = pts[0];
      Core.path(g, d + ` L` + Core.f2(match$1[0]) + `,` + Core.f2(plotH) + ` L` + Core.f2(match$2[0]) + `,` + Core.f2(plotH) + ` Z`, [
        [
          "fill",
          c
        ],
        [
          "opacity",
          "0.12"
        ],
        [
          "stroke",
          "none"
        ]
      ]);
    }
    let dashAttr = s.dashed ? [[
          "stroke-dasharray",
          "5,3"
        ]] : [];
    Core.path(g, d, [
      [
        "fill",
        "none"
      ],
      [
        "stroke",
        c
      ],
      [
        "stroke-width",
        "2"
      ]
    ].concat(dashAttr));
    pts.forEach((param, i) => {
      let py = param[1];
      let px = param[0];
      if (opts.points) {
        Core.circle(g, px, py, 4, [
          [
            "fill",
            c
          ],
          [
            "stroke",
            "#0d1117"
          ],
          [
            "stroke-width",
            "2"
          ]
        ]);
      }
      let target = Core.elIn("circle", [
        [
          "cx",
          Core.f2(px)
        ],
        [
          "cy",
          Core.f2(py)
        ],
        [
          "r",
          "8"
        ],
        [
          "fill",
          "transparent"
        ],
        [
          "style",
          "cursor:pointer"
        ]
      ], g);
      let val_ = s.data[i];
      let lbl = Stdlib_Option.getOr(labels[i], "");
      let name = s.name;
      target.addEventListener("mouseenter", e => Core.showTip(tip, `<b style="color:` + c + `">` + name + `</b><br/>` + lbl + `: <b>` + Core.fmtVal(val_) + `</b>`, e));
      target.addEventListener("mousemove", e => Core.moveTip(tip, e));
      target.addEventListener("mouseleave", param => Core.hideTip(tip));
    });
  });
  Core.line(g, 0, plotH, plotW, plotH, "#30363d", undefined);
  return () => Core.removeTip(tip);
}

export {
  parseSeries,
  parseOptions,
  parseChart,
  make,
}
/* No side effect */
