// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.js";
import * as Belt_Float from "@rescript/runtime/lib/es6/Belt_Float.js";
import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function formatElement(el) {
  let amount = el.getAttribute("data-bal-amount");
  let currency = el.getAttribute("data-bal-currency");
  if (amount == null) {
    return;
  }
  if (currency == null) {
    return;
  }
  let amount$1 = Belt_Option.getWithDefault(Belt_Float.fromString(amount), 0.0);
  let formatter = new Intl.NumberFormat(navigator.language, {
    style: "currency",
    currency: currency,
    maximumFractionDigits: 0
  });
  el.textContent = formatter.format(amount$1);
}

function run() {
  Belt_Array.forEach(Array.from(document.querySelectorAll("[data-bal-amount]")), formatElement);
}

export {
  formatElement,
  run,
}
/* No side effect */
