// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "./Core.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function parseSeries(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let name = json.name;
    if (typeof name === "string") {
      let rawData = json.data;
      if (Array.isArray(rawData)) {
        let data = rawData.map(Core.asFloat);
        let color = Core.optField(json.color, Core.asString);
        return {
          name: name,
          data: data,
          color: color
        };
      }
      throw {
        RE_EXN_ID: Core.InvalidJson,
        _1: {
          TAG: "InvalidData",
          _0: "bah ?"
        },
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidData",
        _0: "bah ?"
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidData",
      _0: "bah ?"
    },
    Error: new Error()
  };
}

function parseOptions(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    return {
      width: Core.optField(json.width, Core.asFloat),
      height: Core.optField(json.height, Core.asFloat),
      labels: Core.optField(json.labels, Core.asStringArray),
      yTicks: Core.optField(json.yTicks, Core.asInt),
      gap: Core.optField(json.gap, Core.asFloat),
      colors: Core.optField(json.colors, Core.asStringArray)
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidOption",
      _0: ""
    },
    Error: new Error()
  };
}

function parseChart(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let rawSeries = json.series;
    if (Array.isArray(rawSeries)) {
      let rawOpts = json.options;
      let series = rawSeries.map(parseSeries);
      let options = rawOpts !== undefined && rawOpts !== null ? parseOptions(rawOpts) : undefined;
      return {
        series: series,
        options: options
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidChart",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidChart",
      _0: ""
    },
    Error: new Error()
  };
}

function make(container, series, opts) {
  let w = Stdlib_Option.getOr(opts.width, 600);
  let h = Stdlib_Option.getOr(opts.height, 280);
  let yTicks = Stdlib_Option.getOr(opts.yTicks, 5);
  let gap = Stdlib_Option.getOr(opts.gap, 0.25);
  let colors = Stdlib_Option.getOr(opts.colors, Core.palette);
  let nGroups = Stdlib_Array.reduce(series, 0, (acc, s) => Primitive_int.max(acc, s.data.length));
  let labels = Stdlib_Option.getOr(opts.labels, Stdlib_Array.fromInitializer(nGroups, i => (i + 1 | 0).toString()));
  let allVals = series.flatMap(s => s.data);
  let maxVal = Core.niceMax(allVals);
  let plotW = w - 50 - 16;
  let plotH = h - 20 - 36;
  let svg = Core.svgEl(w, h, container);
  let g = Core.group(`translate(` + Core.f2(50) + `,` + Core.f2(20) + `)`, svg);
  Core.linspace(0, maxVal, yTicks).forEach(v => {
    let y = plotH - v / maxVal * plotH;
    Core.line(g, 0, y, plotW, y, undefined, undefined);
    Core.text(g, -6, y + 4, Core.fmtVal(v), [
      [
        "text-anchor",
        "end"
      ],
      [
        "fill",
        "#8b949e"
      ],
      [
        "font-size",
        "11"
      ]
    ]);
  });
  let groupW = plotW / nGroups;
  let barTotal = groupW * (1 - gap);
  let barW = barTotal / series.length;
  let tip = Core.makeTooltip();
  for (let gi = 0; gi < nGroups; ++gi) {
    let gx = gi * groupW + groupW * gap / 2;
    let lbl = Stdlib_Option.getOr(labels[gi], "");
    Core.text(g, gx + barTotal / 2, plotH + 18, lbl, [
      [
        "text-anchor",
        "middle"
      ],
      [
        "fill",
        "#8b949e"
      ],
      [
        "font-size",
        "11"
      ]
    ]);
    series.forEach((s, si) => {
      let val_ = Stdlib_Option.getOr(s.data[gi], 0);
      let bx = gx + si * barW;
      let bh = val_ / maxVal * plotH;
      let c = Stdlib_Option.getOr(s.color, Core.getColor(colors, si));
      let name = s.name;
      let r = Core.elIn("rect", [
        [
          "x",
          Core.f2(bx)
        ],
        [
          "y",
          Core.f2(plotH - bh)
        ],
        [
          "width",
          Core.f2(barW - 1)
        ],
        [
          "height",
          Core.f2(bh)
        ],
        [
          "fill",
          c
        ],
        [
          "rx",
          "2"
        ],
        [
          "style",
          "cursor:pointer"
        ]
      ], g);
      r.addEventListener("mouseenter", e => Core.showTip(tip, `<b style="color:` + c + `">` + name + `</b><br/>` + lbl + `: <b>` + Core.fmtVal(val_) + `</b>`, e));
      r.addEventListener("mousemove", e => Core.moveTip(tip, e));
      r.addEventListener("mouseleave", param => Core.hideTip(tip));
    });
  }
  Core.line(g, 0, plotH, plotW, plotH, "#30363d", undefined);
  return () => Core.removeTip(tip);
}

export {
  parseSeries,
  parseOptions,
  parseChart,
  make,
}
/* No side effect */
