// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Bar from "./Bar.res.mjs";
import * as Pie from "./Pie.res.mjs";
import * as Line from "./Line.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";

let months = [
  "Jan",
  "Fév",
  "Mar",
  "Avr",
  "Mai",
  "Juin",
  "Juil",
  "Août",
  "Sep",
  "Oct",
  "Nov",
  "Déc"
];

function walk(n, base, vol) {
  let v = {
    contents: base
  };
  return Stdlib_Array.fromInitializer(n, param => {
    v.contents = v.contents + (Math.random() - 0.49) * vol;
    return (v.contents * 100 | 0) / 100;
  });
}

function init() {
  let element = document.getElementById("bar");
  let exit = 0;
  if (element == null) {
    exit = 1;
  } else {
    Bar.make(element, [
      {
        name: "Produit A",
        data: [
          42,
          58,
          71,
          63,
          89,
          74,
          95,
          82,
          68,
          77,
          91,
          105
        ],
        color: undefined
      },
      {
        name: "Produit B",
        data: [
          28,
          35,
          41,
          55,
          48,
          62,
          58,
          71,
          83,
          69,
          74,
          88
        ],
        color: undefined
      },
      {
        name: "Produit C",
        data: [
          15,
          22,
          18,
          31,
          27,
          34,
          29,
          38,
          42,
          35,
          41,
          55
        ],
        color: undefined
      }
    ], {
      width: 760,
      height: 260,
      labels: months,
      yTicks: undefined,
      gap: undefined,
      colors: undefined
    });
  }
  exit === 1;
  let element$1 = document.getElementById("line");
  let exit$1 = 0;
  if (element$1 == null) {
    exit$1 = 1;
  } else {
    Line.make(element$1, [{
        name: "EUR/USD",
        data: walk(12, 1.085, 0.008),
        color: undefined,
        area: true,
        dashed: false
      }], {
      width: 370,
      height: 220,
      labels: months,
      yTicks: undefined,
      smooth: true,
      points: true,
      colors: undefined
    });
  }
  exit$1 === 1;
  let element$2 = document.getElementById("pie");
  let exit$2 = 0;
  if (element$2 == null) {
    exit$2 = 1;
  } else {
    Pie.make(element$2, [
      {
        label: "Infrastructure",
        value: 34,
        color: undefined
      },
      {
        label: "Marketing",
        value: 22,
        color: undefined
      },
      {
        label: "R&D",
        value: 28,
        color: undefined
      },
      {
        label: "RH",
        value: 10,
        color: undefined
      },
      {
        label: "Divers",
        value: 6,
        color: undefined
      }
    ], {
      width: 370,
      height: 220,
      donut: false,
      donutWidth: undefined,
      padAngle: undefined,
      showLabel: true,
      colors: undefined
    });
  }
  exit$2 === 1;
  let element$3 = document.getElementById("multi");
  let exit$3 = 0;
  if (element$3 == null) {
    exit$3 = 1;
  } else {
    Line.make(element$3, [
      {
        name: "BTC/1k",
        data: walk(12, 42, 3),
        color: undefined,
        area: false,
        dashed: false
      },
      {
        name: "ETH/100",
        data: walk(12, 22, 2),
        color: undefined,
        area: false,
        dashed: true
      },
      {
        name: "SOL",
        data: walk(12, 95, 7),
        color: undefined,
        area: false,
        dashed: true
      }
    ], {
      width: 370,
      height: 220,
      labels: months,
      yTicks: undefined,
      smooth: true,
      points: false,
      colors: undefined
    });
  }
  exit$3 === 1;
  let element$4 = document.getElementById("donut");
  let exit$4 = 0;
  if (element$4 == null) {
    exit$4 = 1;
  } else {
    Pie.make(element$4, [
      {
        label: "Complété",
        value: 63,
        color: undefined
      },
      {
        label: "En cours",
        value: 20,
        color: undefined
      },
      {
        label: "En attente",
        value: 17,
        color: undefined
      }
    ], {
      width: 370,
      height: 220,
      donut: true,
      donutWidth: 45,
      padAngle: undefined,
      showLabel: true,
      colors: undefined
    });
  }
  exit$4 === 1;
}

window.addEventListener("DOMContentLoaded", init);

export {
  months,
  walk,
  init,
}
/*  Not a pure module */
