// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core from "./Core.res.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Primitive_float from "@rescript/runtime/lib/es6/Primitive_float.js";

function parseSlice(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let label = json.label;
    if (typeof label === "string") {
      let value = json.value;
      if (typeof value === "number") {
        let color = Core.optField(json.color, Core.asString);
        return {
          label: label,
          value: value,
          color: color
        };
      }
      throw {
        RE_EXN_ID: Core.InvalidJson,
        _1: {
          TAG: "InvalidData",
          _0: ""
        },
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidData",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidData",
      _0: ""
    },
    Error: new Error()
  };
}

function parseOptions(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let donut = json.donut;
    if (typeof donut === "boolean") {
      let showLabel = json.showLabel;
      if (typeof showLabel === "boolean") {
        return {
          width: Core.optField(json.width, Core.asFloat),
          height: Core.optField(json.height, Core.asFloat),
          donut: donut,
          donutWidth: Core.optField(json.donutWidth, Core.asFloat),
          padAngle: Core.optField(json.padAngle, Core.asFloat),
          showLabel: showLabel,
          colors: Core.optField(json.colors, Core.asStringArray)
        };
      }
      throw {
        RE_EXN_ID: Core.InvalidJson,
        _1: {
          TAG: "InvalidOption",
          _0: ""
        },
        Error: new Error()
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidOption",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidOption",
      _0: ""
    },
    Error: new Error()
  };
}

function parseChart(json) {
  if (typeof json === "object" && json !== null && !Array.isArray(json)) {
    let rawSlices = json.slices;
    if (Array.isArray(rawSlices)) {
      let rawOpts = json.options;
      let slices = rawSlices.map(parseSlice);
      let options = rawOpts !== undefined && rawOpts !== null ? parseOptions(rawOpts) : undefined;
      return {
        slices: slices,
        options: options
      };
    }
    throw {
      RE_EXN_ID: Core.InvalidJson,
      _1: {
        TAG: "InvalidChart",
        _0: ""
      },
      Error: new Error()
    };
  }
  throw {
    RE_EXN_ID: Core.InvalidJson,
    _1: {
      TAG: "InvalidChart",
      _0: ""
    },
    Error: new Error()
  };
}

function arcPath(cx, cy, r, ir, start, end_) {
  let x1 = cx + r * Math.cos(start);
  let y1 = cy + r * Math.sin(start);
  let x2 = cx + r * Math.cos(end_);
  let y2 = cy + r * Math.sin(end_);
  let large = end_ - start > Math.PI ? "1" : "0";
  if (ir === 0) {
    return `M` + Core.f2(cx) + `,` + Core.f2(cy) + ` L` + Core.f2(x1) + `,` + Core.f2(y1) + ` A` + Core.f2(r) + `,` + Core.f2(r) + ` 0 ` + large + `,1 ` + Core.f2(x2) + `,` + Core.f2(y2) + ` Z`;
  }
  let ix1 = cx + ir * Math.cos(end_);
  let iy1 = cy + ir * Math.sin(end_);
  let ix2 = cx + ir * Math.cos(start);
  let iy2 = cy + ir * Math.sin(start);
  return `M` + Core.f2(x1) + `,` + Core.f2(y1) + ` A` + Core.f2(r) + `,` + Core.f2(r) + ` 0 ` + large + `,1 ` + Core.f2(x2) + `,` + Core.f2(y2) + ` ` + (`L` + Core.f2(ix1) + `,` + Core.f2(iy1) + ` A` + Core.f2(ir) + `,` + Core.f2(ir) + ` 0 ` + large + `,0 ` + Core.f2(ix2) + `,` + Core.f2(iy2) + ` Z`);
}

function make(container, slices, opts) {
  let w = Stdlib_Option.getOr(opts.width, 280);
  let h = Stdlib_Option.getOr(opts.height, 240);
  let colors = Stdlib_Option.getOr(opts.colors, Core.palette);
  let donutW = Stdlib_Option.getOr(opts.donutWidth, 40);
  let padAng = Stdlib_Option.getOr(opts.padAngle, 0.018);
  let cx = w / 2;
  let cy = h / 2;
  let r = Primitive_float.min(cx, cy) - 8;
  let ir = opts.donut ? r - donutW : 0;
  let total = Stdlib_Array.reduce(slices, 0, (acc, s) => acc + s.value);
  let svg = Core.svgEl(w, h, container);
  let tip = Core.makeTooltip();
  let angle = {
    contents: - Math.PI / 2
  };
  slices.forEach((sl, i) => {
    let pct = sl.value / total;
    let span = pct * 2 * Math.PI - padAng;
    let c = Stdlib_Option.getOr(sl.color, Core.getColor(colors, i));
    let mid = angle.contents + span / 2;
    let d = arcPath(cx, cy, r, ir, angle.contents, angle.contents + span);
    let p = Core.elIn("path", [
      [
        "d",
        d
      ],
      [
        "fill",
        c
      ],
      [
        "stroke",
        "#0d1117"
      ],
      [
        "stroke-width",
        "1"
      ],
      [
        "style",
        "cursor:pointer"
      ]
    ], svg);
    if (opts.showLabel && pct > 0.05) {
      let lr = ir > 0 ? (r + ir) / 2 : r * 0.65;
      let lx = cx + lr * Math.cos(mid);
      let ly = cy + lr * Math.sin(mid);
      Core.text(svg, lx, ly, (pct * 100).toFixed(0) + `%`, [
        [
          "text-anchor",
          "middle"
        ],
        [
          "dominant-baseline",
          "middle"
        ],
        [
          "fill",
          "#fff"
        ],
        [
          "font-size",
          "11"
        ],
        [
          "font-weight",
          "600"
        ],
        [
          "style",
          "pointer-events:none"
        ]
      ]);
    }
    let pctStr = (pct * 100).toFixed(0) + `%`;
    let lbl = sl.label;
    let val_ = sl.value;
    p.addEventListener("mouseenter", e => {
      Core.showTip(tip, `<b style="color:` + c + `">` + lbl + `</b><br/>` + pctStr + ` (` + Core.fmtVal(val_) + `)`, e);
      p.setAttribute("transform", `translate(` + Core.f2(Math.cos(mid) * 4) + `,` + Core.f2(Math.sin(mid) * 4) + `)`);
    });
    p.addEventListener("mousemove", e => Core.moveTip(tip, e));
    p.addEventListener("mouseleave", param => {
      Core.hideTip(tip);
      p.removeAttribute("transform");
    });
    angle.contents = angle.contents + span + padAng;
  });
  if (opts.donut) {
    Core.text(svg, cx, cy, Core.fmtVal(total), [
      [
        "text-anchor",
        "middle"
      ],
      [
        "dominant-baseline",
        "middle"
      ],
      [
        "fill",
        "#e6edf3"
      ],
      [
        "font-size",
        "14"
      ],
      [
        "font-weight",
        "700"
      ]
    ]);
  }
  return () => Core.removeTip(tip);
}

export {
  parseSlice,
  parseOptions,
  parseChart,
  arcPath,
  make,
}
/* No side effect */
