[env]
DATABASE_URL = "postgres://postgres:@localhost:5432/maille"
TRACING_ENDPOINT="docker-monitoring-collector.docker-monitoring_public:4317"

[tasks.set-secret]
usage = '''
arg "<secret>" help="password of database/and pod database secret"
'''
run = '''#!/usr/bin/elvish
  var a = (echo $E:usage_secret | base64 -w0); printf '{"password": "'$a'"}'"\n" | podman secret create --replace maille-database -
  var a = (printf 'postgres://maille:'$E:usage_secret'@postgres:5432/maille' | base64 -w0); printf '{"database": "'$a'"}'"\n" | podman secret create --replace maille-database-url -
'''

[tasks.build]
run = "podman build --layers -t localhost/maille-dev:latest -f deploy/Containerfile.dev ."

[tasks.deploy-network]
run = "podman network create maille-network"

[tasks.deploy-postgresql]
run = "podman play kube --network maille-network --replace deploy/postgresql.yaml"

[tasks.deploy-pod]
run = "podman play kube --network maille-network --network docker-monitoring_public --replace deploy/dev-pod.yaml"

[tasks.deploy]
depends = ["build", "deploy-network", "deploy-postgresql", "deploy-pod"]
